on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Ensure the consistency between the python versions described as supported vs versions we actually support
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check if all the supported python versions are consistent
      uses: actions/setup-python@v5
    - name: Install checker
      run: |
        python -m pip install --upgrade pip
        python -m pip install check-python-versions
    - name: Check
      run: |
        check-python-versions